import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import ReduxProvider from "@/Redux/ReduxProviders";
import { Directions, Languages } from "@/contants/enums";
import { getCurrentLocale } from "@/lib/getCurrentLocale";

/// Font Family & Weight
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["200", "300", "400"],
  /// تجهيز الفونت فاميلي عند عرض الصفحة
  preload: true,
});

export const metadata: Metadata = {
  title: "Food Ordering App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getCurrentLocale();

  return (
    <html
      lang={locale}      
      dir={locale === Languages.ENGLISH ? Directions.LTR : Directions.RTL}
    >
      <body className={roboto.className}>
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
